### ISSUE TITLE
import 'curry-this/module'

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/curry-this#18]
`import {curry, _} from 'curry-this/module';`
This doesn't work for me. It works if you are in the same module, but it breaks if you try this with an installed module.

```
(function (exports, require, module, __filename, __dirname) { import placehold
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:409:25)
    at Module._extensions..js (module.js:444:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/nod

e_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/stoeffel/src/nmotw.curry-this/curry.js:5:24)
    at Module._compile (module.js:426:26)
```

// cc @tomekwi any ideas how to fix this?

**Comment by stoeffel** [comment]
and importing the transpiled one doesn't work either.

**Comment by stoeffel** [comment]
I think we should just push the transpiled version to npm. and change the doc of how to require the lib.

**Comment by stoeffel** [comment]
Or maybe something like this:
```js
export const _ = placeholder({Symbol});
export const curry = curryFunction({placeholder: _});

export const polyfill = ({Symbol}) => {
  return {
    _: placeholder({Symbol}),
    curry: curryFunction({placeholder: _}),
  };
};
```

**Comment by tomekwi** [comment]
Do ES 2015 imports work for other modules for you? *babel* ignores `node_modules` by default – and I remember I had a hard time trying to convince it to transpile dependencies. The error message looks exactly like the one I had back then.

**Comment by stoeffel** [comment]
nope, they don't work. I think this is not possible with babel. did you make it work, back then? If this doesn't work with babel I vote that we change the api like proposed in my pr or maybe like I proposed ^. what do you think?

**Comment by tomekwi** [comment]
> did you make it work, back then?

Nope. But it does work when I bundle stuff for the browser with *webpack* and *babel-loader*.

> I vote that we change the api

I don’t think changing the API because some tool doesn’t support a language feature is a good idea. After all, we’re writing ES 2015 because it will soon be all available natively – aren’t we?

We can change the docs though, and encourage using the `require` option.

**Comment by stoeffel** [comment]
> I don’t think changing the API because some tool doesn’t support a language feature is a good idea. After all, we’re writing ES 2015 because it will soon be all available natively – aren’t we?

You are right.

> We can change the docs though, and encourage using the require option.

let's do that.

**Comment by tomekwi** [comment]
:+1:

**Comment by tomekwi** [comment]
https://github.com/stoeffel/curry-this/releases/tag/v3.0.1
