### ISSUE TITLE
Requires global polyfill for Symbol

### ISSUE THREAD

**Issue by tomekwi** [stoeffel/curry-this#25]
http://requirebin.com/?gist=b96f3f9c9aae5a5b6edc

That means the thing doesn’t work in an ES5 environment. Even using transpiled code.

Alternative: https://www.npmjs.com/package/es6-symbol (use global when available, otherwise polyfill).

**Comment by tomekwi** [comment]
BTW, the bin I posted results in an `Uncaught TypeError: Cannot read property 'Symbol' of undefined` on Chromium v43.

**Comment by stoeffel** [comment]
Arg. How about we drop using a Symbol and use a string like `__CURRY-THIS__`.

**Comment by tomekwi** [comment]
Well, Symbol is designed specifically for things like this. However unlikely it is, running `replace::curry(/__/g, _, '__CURRY-THIS__')('😃')` should return `'😃CURRY-THIS😃'` but wouldn’t. And Symbol is bulletproof against this stuff.

And second thing – comparing any string to `'__CURRY-THIS__'` costs more than comparing two Symbols. So a teeny weeny performance benefit.

We do want it perfect, don’t we? 😃

**Comment by tomekwi** [comment]
Duh, how stupid of me. I forgot about https://github.com/stoeffel/curry-this/tree/6bc7e04b1fec2bb9624435974687964e7f398ff8#symbol-polyfill – all the fuss. We may as well close this thing./cc @davidchase

**Comment by stoeffel** [comment]
Yeah, perfect is always better😊. If we stick with the Symbol one just has to polifill Symbol like described in the readme. https://github.com/stoeffel/curry-this#symbol-polyfill
So in this case we can close this issue, right?

**Comment by tomekwi** [comment]
:8ball:

**Comment by tomekwi** [comment]
Haha, sorry again!

**Comment by stoeffel** [comment]
:laughing: btw one can always do [this](https://github.com/stoeffel/compose-function#with-curry)

**Comment by davidchase** [comment]
@tomekwi @stoeffel you don't want to provide that symbol polyfill to the user? so instead of the users pulling in the `es6-symbol` you can offer it internally as polyfill if symbol doesn't exist within the user land env or do you guys prefer the byos (bring your own symbols) approach... just curious

**Comment by stoeffel** [comment]
> so instead of the users pulling in the es6-symbol you can offer it internally as polyfill if symbol doesn't exist within the user land env or do you guys prefer the byos (bring your own symbols) approach... just curious

Yeah, you are right. I actually don't like this byos approach not one bit. I reopened my PR and changed it to depend on 'es6-symbol`. What say @tomekwi, @davidchase?

**Comment by rtm** [comment]
Confused by this entire discussion. We just need a unique object which we can `===` against. The object `var placeholder = {};` works fine. The equality comparison is as fast as anything else could be--strict object equality. Comparing two pointers.

Yes, one could use Symbol for this, but there's no need to, and it brings up the whole polyfill/environmental issue. Actually, it's not exactly correct to say "Symbol is designed specifically for things like this". The main use case for Symbol is as unique property keys.

Check out the PR #31. It works fine with `{}` as a unique object for placeholder.

**Comment by tomekwi** [comment]
> Confused by this entire discussion.

@rtm Actually, this thing has a longer history. Originally I wanted to let the user decide what he’s going to use as a placeholder: https://github.com/stoeffel/curry-this/issues/7#issuecomment-124900672. After a while I forgot about this API and got confused when trying to use the lib in an ES5 environment. Hence this issue.

> We just need a unique object which we can === against. The object var placeholder = {}; works fine.

I actually use `{}` for this purpose whenever I don’t have access to a native `Symbol`. I only see one disadvantage – it doesn’t say much when you inspect the value with dev tools.

> there's no need to, and it brings up the whole polyfill/environmental issue.

I must say you’re right. After all the fuss I made around the topic, I confess we should have Kept It Stupid Simple from the very beginning. Do you agree @stoeffel @davidchase?

**Comment by stoeffel** [comment]
> I only see one disadvantage – it doesn’t say much when you inspect the value with dev tools.

Yop, but we could do it like ramda and use something like `{ placeholder: 'curry-this' }`.

>  I confess we should have Kept It Stupid Simple from the very beginning

Simple is always better.

**Comment by tomekwi** [comment]
> we could do it like ramda and use something like { placeholder: 'curry-this' }.

:+1: I do that myself too!

**Comment by stoeffel** [comment]
Okay let's go with `{ placeholder: 'curry-this' }`.
@rtm could you update the PR #31?
